# Generated by Django 4.0.4 on 2022-06-15 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dietetyk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element_of_meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, unique=True)),
                ('gram_per_100gr', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Element_of_meal',
                'verbose_name_plural': 'Element_of_meals',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, unique=True)),
                ('sex', models.IntegerField(choices=[(1, 'Filet z soli z ryżem i warzywami'), (2, 'Ratatouille z indyka'), (3, 'Sałatka z Mango i kurczakiem'), (4, 'Zapiekana na kurczakiem'), (5, 'Dorsz gotowany'), (6, 'Zupa pomidorowa'), (7, 'Leczo z piersią indyczą')])),
                ('age', models.IntegerField()),
                ('growth', models.IntegerField()),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('element', models.ManyToManyField(to='dietetyk.element_of_meals')),
                ('meals', models.ManyToManyField(to='dietetyk.meals')),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dietetyk.note')),
                ('user', models.ManyToManyField(to='dietetyk.user')),
            ],
            options={
                'verbose_name': 'Dieta',
                'verbose_name_plural': 'Dietas',
            },
        ),
    ]
