# Generated by Django 4.0.4 on 2022-06-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietetyk', '0004_remove_dieta_meals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meals',
            old_name='product',
            new_name='products',
        ),
    ]
