# Generated by Django 4.0.4 on 2022-06-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietetyk', '0006_dieta_element_dieta_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='products',
            field=models.TextField(),
        ),
    ]
