# Generated by Django 4.0.4 on 2022-06-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietetyk', '0007_alter_meals_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dieta',
            name='created',
        ),
    ]
