# Generated by Django 4.0.4 on 2022-06-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietetyk', '0008_remove_dieta_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element_of_meals',
            name='product',
            field=models.IntegerField(choices=[(1, 'Onion'), (2, 'Bread'), (3, 'Potato'), (4, 'Tomato'), (5, 'Salat'), (6, 'Chicken'), (7, 'Fish')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(1, 'male'), (2, 'female')]),
        ),
    ]
